# Generated by Django 3.1.1 on 2021-03-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_sendinginfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendinginfo',
            name='user',
        ),
        migrations.AddField(
            model_name='sendinginfo',
            name='Rgender',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
