# Generated by Django 3.1.1 on 2021-03-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210307_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendinginfo',
            name='CommissionGivingAmt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sendinginfo',
            name='ContactEmail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sendinginfo',
            name='TotalSalesAmt',
            field=models.IntegerField(),
        ),
    ]
