# Generated by Django 3.1.1 on 2021-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210307_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendinginfo',
            name='TransactionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
