# Generated by Django 3.1.1 on 2021-03-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210307_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendinginfo',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
