# Generated by Django 3.1.1 on 2021-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210307_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendinginfo',
            name='CommissionGivingAmt',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='ContactEmail',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='ProductDetails',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='RAddress',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='RCIN',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='RCountry',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='RPhone',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='Rgender',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='Rname',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='ShopkeeperName',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='TotalSalesAmt',
        ),
        migrations.RemoveField(
            model_name='sendinginfo',
            name='TransactionStatus',
        ),
        migrations.AddField(
            model_name='sendinginfo',
            name='email',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
