# Generated by Django 3.1.1 on 2021-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210307_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendinginfo',
            name='email',
        ),
        migrations.AddField(
            model_name='sendinginfo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendinginfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendinginfo',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
